### ISSUE TITLE
Fix metadata extraction from the title

### ISSUE THREAD

**Issue by swapnilraj** [JorikSchellekens/lyricist#11]
The current way of extracting the artist name and the song title do not account for the the fact that the song title can have dashes in it.

Example Kasabian - Re-wired, with the current approach the the metadata object looks like :- 
``` javascript
{
  artist: 'Kasabian - Re',
  title: 'wired',
}
```

**Comment by swapnilraj** [comment]
I have a [proposal](https://gist.github.com/swapnilraj/7d594835271d609c559706b550e91d2d) for fixing this issue, would appreciate your comments/thoughts @JorikSchellekens.

**Comment by JorikSchellekens** [comment]
I've left some comments on the Gist. Small edits to the proposal but basically the second solution seems the best.

**Comment by JorikSchellekens** [comment]
Will you PR?

**Comment by swapnilraj** [comment]
Yeah I have the PR ready I'll just polish it a bit.
